"""
Django settings for topperblog project.

Generated by 'django-admin startproject' using Django 3.2a1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-65-i)mqzq419hdry8hl(j%27dlpy1(u01-q2##xjag&a9a$qk!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
AUTH_USER_MODEL = 'blogger.User'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'phone_field',

    'drf_yasg',
    'rest_framework',
    'rest_framework_simplejwt',

    'blogger',
    'cdi',
    
    'rest_framework_swagger',
]

BASE_URL = "http://127.0.0.1:8000"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'topperblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
        
    },
]

WSGI_APPLICATION = 'topperblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     # "https://sub.example.com",
#     # "http://localhost:8080",
#     # "http://127.0.0.1:9000"
# ]

# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS = (
#         os.path.join(BASE_DIR, 'static'),
#     )

MEDIA_URL = '/media/'
MEDIA_CUSTOM_DIRS = (
        os.path.join(BASE_DIR, 'media'),
    )

# Default primary key field type
# https://docs.djangoproject.com/en/dev/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
        'blogger.utils.PlainTextParser'
     ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
 }

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": True,
    "brand_colour": "navbar-white",
    "accent": "accent-teal",
    "navbar": "navbar-navy navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-light-navy",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "flatly",
    "dark_mode_theme": None
}

JAZZMIN_SETTINGS = {
    "site_title": "BlogDi Admin",
    "site_header": "BlogDi Admin",
    "site_logo": "images/cover icon.png",
    "welcome_sign": "Welcome to BlogDi Admin",
    "copyright": "circledi Ltd",
    "search_model": "blogger.User",
    "user_avatar": 'profile_picture',
    "icons": {
        "blogger": "fas fa-users-cog",
        "blogger.user": "fab fa-blogger-b",
        "blogger.post": "fas fa-blog",
        "blogger.comment": "fas fa-comments",
        "blogger.favourite": "fas fa-heart",
        "blogger.like": "fas fa-thumbs-up",
        "blogger.postview": "fas fa-eye",
        "blogger.category": "fas fa-bezier-curve",
        "blogger.contact": "fas fa-id-card-alt",
        "blogger.goal": "fas fa-bullseye",
        "blogger.industry": "fas fa-industry",
        "blogger.interest": "fas fa-map-marked-alt",
        "blogger.newslettersubscriber": "fas fa-envelope-open-text",
        "blogger.aboutpage": "fas fa-file-alt",
        "blogger.contactpage": "fas fa-file-alt",
        "blogger.stage": "fas fa-shoe-prints",
        "blogger.tag": "fas fa-tags",

        "cdi.activeadminmodel": "fas fa-tablets",
        "cdi.activecompany": "fas fa-building",

        "admin.LogEntry": "fas fa-file",
    },
    "show_ui_builder": True
}
