# Generated by Django 3.1.6 on 2021-02-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeadminmodel',
            name='app_level',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
