# Generated by Django 3.1.6 on 2021-03-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi', '0002_activeadminmodel_app_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeadminmodel',
            name='admin',
            field=models.BooleanField(default=True),
        ),
    ]
