# Generated by Django 3.1.6 on 2021-03-26 15:59

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi', '0003_activeadminmodel_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activecompany',
            old_name='name',
            new_name='entry_name',
        ),
        migrations.AddField(
            model_name='activecompany',
            name='active_period',
            field=models.CharField(default='nan', max_length=30),
        ),
        migrations.AddField(
            model_name='activecompany',
            name='domain',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activecompany',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activecompany',
            name='license_key',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activecompany',
            name='phone',
            field=phone_field.models.PhoneField(default='', max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activecompany',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activecompany',
            name='zip_postal_code',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
