# Generated by Django 3.1.6 on 2021-02-13 17:16

import blogger.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='_id_slug',
            field=models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='_id_slug',
            field=models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='_id_slug',
            field=models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='_id_slug',
            field=models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='_id_slug',
            field=models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='_id_slug',
            field=models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='_id_slug',
            field=models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='postview',
            name='_id_slug',
            field=models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='_id_slug',
            field=models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='_id_slug',
            field=models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='_id_slug',
            field=models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True),
        ),
    ]
