# Generated by Django 3.1.6 on 2021-03-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_auto_20210305_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-published']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
