# Generated by Django 3.1.6 on 2021-03-11 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0005_auto_20210307_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postview',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
