# Generated by Django 3.1.6 on 2021-03-11 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0006_auto_20210311_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='postview',
            name='create_date',
        ),
    ]
