# Generated by Django 3.1.6 on 2021-03-12 10:38

import blogger.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0008_auto_20210311_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id_slug', models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True)),
                ('page_title', models.CharField(default='About', max_length=255)),
                ('page_head', models.TextField()),
                ('page_main', models.TextField()),
                ('page_footer', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id_slug', models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True)),
                ('page_title', models.CharField(default='Contact', max_length=255)),
                ('page_head', models.TextField()),
                ('page_main', models.TextField()),
                ('page_footer', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
