# Generated by Django 3.1.6 on 2021-03-12 15:04

import blogger.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0009_aboutpage_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id_slug', models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
