# Generated by Django 3.1.6 on 2021-03-14 02:58

import blogger.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0011_auto_20210312_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id_slug', models.SlugField(default=blogger.utils.get_unique_path, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('hp', 'Support'), ('td', 'Trending'), ('wg', 'Warning')], default='hp', max_length=2)),
                ('status', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
