# Generated by Django 3.1.6 on 2021-03-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0012_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
