# Generated by Django 3.1.6 on 2021-03-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0014_auto_20210318_0618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'ordering': ['-create_date'], 'verbose_name': 'Pages - About', 'verbose_name_plural': 'Pages - About'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-priority', 'title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-published'], 'verbose_name': 'Blog Comment', 'verbose_name_plural': 'Blogs Comments'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-create_date'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={'ordering': ['-create_date'], 'verbose_name': 'Pages - Contact', 'verbose_name_plural': 'Pages - Contact'},
        ),
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['-create_date'], 'verbose_name': 'Blog Favourite', 'verbose_name_plural': 'Blogs Favourites'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-priority', 'title'], 'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['-priority', 'title'], 'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['-priority', 'title'], 'verbose_name': 'Interest', 'verbose_name_plural': 'Interests'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-create_date'], 'verbose_name': 'Blog Like', 'verbose_name_plural': 'Blogs Likes'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-create_date'], 'verbose_name': 'Newsletter Subscriber', 'verbose_name_plural': 'Newsletter Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published', 'title'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='postview',
            options={'ordering': ['-view_count'], 'verbose_name': 'Blog Viewed', 'verbose_name_plural': 'Blogs Viewed'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['-priority', 'title'], 'verbose_name': 'Stage', 'verbose_name_plural': 'Stages'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-priority', 'title'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-update_date', '-create_date'], 'verbose_name': 'Blogger', 'verbose_name_plural': 'Bloggers'},
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='dummy-profile-pic-male.jpg', null=True, upload_to=''),
        ),
    ]
