# Generated by Django 3.1.6 on 2021-03-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0015_auto_20210324_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goals',
            field=models.ManyToManyField(null=True, to='blogger.Goal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogger.industry'),
        ),
    ]
