# Generated by Django 3.1 on 2021-04-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0017_auto_20210415_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='dummy-profile-pic-male.jpg', null=True, upload_to='media'),
        ),
    ]
